import { useEffect, useState } from "react";

import { usePairingStore } from "../stores/pairingStore";
import type { DeviceScope, PairedDevice, PendingPairing } from "../types/domain";

const SCOPE_LABEL: Record<DeviceScope, string> = {
  readOnly: "read only",
  readApprovals: "read + approvals",
  full: "full (can drive)",
};

const SCOPES: DeviceScope[] = ["readOnly", "readApprovals", "full"];

export function DevicesPanel() {
  const offer = usePairingStore((s) => s.offer);
  const starting = usePairingStore((s) => s.starting);
  const pending = usePairingStore((s) => s.pending);
  const devices = usePairingStore((s) => s.devices);
  const error = usePairingStore((s) => s.error);
  const startPairing = usePairingStore((s) => s.startPairing);
  const refresh = usePairingStore((s) => s.refresh);
  const simulateIncoming = usePairingStore((s) => s.simulateIncoming);

  // Poll while the panel is open so scanned/incoming pairings surface.
  useEffect(() => {
    void refresh();
    const t = setInterval(() => void refresh(), 2000);
    return () => clearInterval(t);
  }, [refresh]);

  return (
    <div className="workbench">
      <div className="workbench-header workbench-header-slim">
        <span className="workbench-title">devices</span>
        <span className="spacer" />
        <button className="workbench-action" onClick={() => void refresh()} title="Refresh">↻</button>
      </div>

      <div className="workbench-body">
        {error && (
          <section className="wb-section">
            <p className="wb-hint" style={{ color: "#ff8585", whiteSpace: "pre-wrap" }}>{error}</p>
          </section>
        )}

        {/* Pair a new device */}
        <section className="wb-section">
          <div className="wb-section-title">pair a phone</div>
          {offer ? (
            <PairingOfferView />
          ) : (
            <>
              <p className="wb-hint">
                Show a one-time QR for your phone to scan. Pairing only completes
                after you approve it here — the QR alone is not enough.
              </p>
              <button className="wb-cta" onClick={() => void startPairing()} disabled={starting}>
                {starting ? "…" : "Show pairing QR"}
              </button>
            </>
          )}
        </section>

        {/* Pending approvals */}
        {pending.length > 0 && (
          <section className="wb-section">
            <div className="wb-section-title">
              awaiting approval
              <span className="wb-count">{pending.length}</span>
            </div>
            <ul className="wb-advisor-list">
              {pending.map((p) => <PendingRow key={p.id} pending={p} />)}
            </ul>
          </section>
        )}

        {/* Paired devices */}
        <section className="wb-section">
          <div className="wb-section-title">
            paired devices
            <span className="wb-count">{devices.length}</span>
          </div>
          {devices.length === 0 ? (
            <p className="wb-hint">No devices paired yet.</p>
          ) : (
            <ul className="wb-advisor-list">
              {devices.map((d) => <DeviceRow key={d.id} device={d} />)}
            </ul>
          )}
        </section>

        {/* Dev affordance until the transport feeds real handshakes (Hito 5). */}
        <section className="wb-section">
          <button className="wb-link" onClick={() => void simulateIncoming()}>
            simulate an incoming pairing (dev)
          </button>
        </section>
      </div>
    </div>
  );
}

function PairingOfferView() {
  const offer = usePairingStore((s) => s.offer)!;
  const clearOffer = usePairingStore((s) => s.clearOffer);
  const [remaining, setRemaining] = useState(() =>
    Math.max(0, Math.floor((offer.expiresAtMs - Date.now()) / 1000)),
  );

  useEffect(() => {
    const t = setInterval(() => {
      setRemaining(Math.max(0, Math.floor((offer.expiresAtMs - Date.now()) / 1000)));
    }, 1000);
    return () => clearInterval(t);
  }, [offer.expiresAtMs]);

  const expired = remaining <= 0;

  return (
    <div className="wb-pairing-offer">
      <div
        className={`wb-qr ${expired ? "expired" : ""}`}
        // The SVG is generated by our own backend from the offer — not remote content.
        dangerouslySetInnerHTML={{ __html: offer.qrSvg }}
      />
      <p className="wb-hint">
        {expired
          ? "This code expired. Generate a new one."
          : `Scan with your phone. Expires in ${remaining}s.`}
      </p>
      <button className="wb-link" onClick={clearOffer}>done</button>
    </div>
  );
}

function PendingRow({ pending }: { pending: PendingPairing }) {
  const approve = usePairingStore((s) => s.approve);
  const reject = usePairingStore((s) => s.reject);
  const [scope, setScope] = useState<DeviceScope>(pending.proposedScope);
  const [busy, setBusy] = useState(false);

  return (
    <li className="wb-advisor">
      <div className="wb-advisor-body" style={{ display: "block" }}>
        <div className="wb-advisor-name">{pending.label}</div>
        <div className="wb-advisor-desc" style={{ wordBreak: "break-all" }}>
          {pending.publicKey.slice(0, 24)}…
        </div>
        <div className="wb-advisor-controls">
          <label className="wb-advisor-scope">
            <span>scope</span>
            <select value={scope} onChange={(e) => setScope(e.target.value as DeviceScope)} disabled={busy}>
              {SCOPES.map((s) => <option key={s} value={s}>{SCOPE_LABEL[s]}</option>)}
            </select>
          </label>
          <div className="wb-advisor-actions">
            <button className="wb-link" onClick={() => void reject(pending.id)} disabled={busy}>reject</button>
            <button
              className="wb-cta wb-cta-sm"
              disabled={busy}
              onClick={() => { setBusy(true); void approve(pending.id, scope); }}
            >
              Approve
            </button>
          </div>
        </div>
      </div>
    </li>
  );
}

function DeviceRow({ device }: { device: PairedDevice }) {
  const setScope = usePairingStore((s) => s.setScope);
  const revoke = usePairingStore((s) => s.revoke);

  return (
    <li className="wb-advisor">
      <div className="wb-advisor-body" style={{ display: "block" }}>
        <div className="wb-advisor-name">{device.label}</div>
        <div className="wb-advisor-controls">
          <label className="wb-advisor-scope">
            <span>scope</span>
            <select
              value={device.scope}
              onChange={(e) => void setScope(device.id, e.target.value as DeviceScope)}
            >
              {SCOPES.map((s) => <option key={s} value={s}>{SCOPE_LABEL[s]}</option>)}
            </select>
          </label>
          <div className="wb-advisor-actions">
            <button className="wb-link" onClick={() => void revoke(device.id)}>revoke</button>
          </div>
        </div>
      </div>
    </li>
  );
}
